### ISSUE TITLE
Nominations and Vote for President

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#11]
Position currently held informally by @wrumsby whom I nominate again

**Comment by Unfocused** [comment]
Seconded for @wrumsby

**Comment by Unfocused** [comment]
@wrumsby - could you provide a short bio/blurb/whatever. Just something to give people context as to why you think you should be voted in.

**Comment by wrumsby** [comment]
Short bio/blurb/whatever:

I'm Walter, I've been enjoying programming with JavaScript since 1998 and have been running the Auckland JavaScript Meetup since 2011. I like JavaScript.

**Comment by wrumsby** [comment]
Walter appointed President with 10 :+1: votes.
