### ISSUE TITLE
Nominations and Vote for Secretary

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#12]
Position currently held by @Unfocused whom I nominate again

**Comment by phenomnomnominal** [comment]
seconded for @Unfocused

**Comment by Unfocused** [comment]
So.....

Ohai! I'm Blair. I'm a senior engineer at Mozilla, where the main part of my job is building Firefox (primarily using web technologies like JavaScript). Additionally I end up doing a lot of mentoring, and general evangelism for the open web. Separately, I've also co-founded and previously acted as secretary for the Dunedin Makerspace.

I've been JS-NZ secretary for the past year, which has involved drafting our society rules and codes of conduct, writing member newsletters, setting up support services, and generally supporting the rest of the society & committee. I see a lot of potential in our Society, in being an inclusive community that that can do more together - from connecting people, to sharing resources that enable things like Nodebots for novices and conferences for seasoned professionals.

**Comment by wrumsby** [comment]
Blair appointed Secretary with 11 :+1: votes.
