### ISSUE TITLE
Nominations and Vote for Officers

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#13]
General officer positions currently held by 

@phenomnomnominal 
@jenofdoom 
@Kevnz 
@buildmaster
@vimto

**Comment by buildmaster** [comment]
I'm happy to put myself forward for the role again

@buildmaster nominates @buildmaster

**Comment by jenofdoom** [comment]
I'm happy to serve again. I am nominating myself, Jen Zajac (@jenofdoom)

**Comment by Unfocused** [comment]
Seconded for @buildmaster and @jenofdoom

**Comment by phenomnomnominal** [comment]
Keen to stay on and keep learning how this all works. @phenomnomnominal nominates @phenomnomnominal

**Comment by Unfocused** [comment]
Seconded @phenomnomnominal

Also nominating @vimto and @Kevnz, although they haven't yet explicitly stated whether they're open to continuing in their roles.

**Comment by PrototypeAlex** [comment]
If anyone want's to drop out, I know @GrahamJenson is keen to join as an officer, he'll be back from the UK in October, but can help remotely for the time being.

**Comment by grahamjenson** [comment]
I nominate myself @grahamjenson.

**Comment by vimto** [comment]
Thanks Blair. Keen to stick around too to keep learning how this works, and
hopefully should have more time to contribute this coming year.

So seconding myself @vimto. (Is that possible?).

**Comment by Unfocused** [comment]
> I nominate myself @grahamjenson. 

Seconded

**Comment by Unfocused** [comment]
> So seconding myself @vimto. (Is that possible?).

I'm going with "yes", on the basis the rules state you can nominate yourself, and seconding is basically just nominating but you weren't the first to do it.

**Comment by PrototypeAlex** [comment]
How many officers are we looking for? 

We did discuss the number of officers at the beginning, and restricted it for a reason that's eluded me, anyone remember? or was it that we wanted an odd number of officers?

**Comment by Unfocused** [comment]
Thanks for the reminder, I've been meaning to comment on that.

That there is no specific limitations around the size of the committee. As long as we have 3 on the committee to cover president/treasurer/secretary. Anything above that, the number can be determined freely by the society each year.

However... 

A year ago we discussed this somewhat, and decided that 5 was a good number, and likely a good upper bound until the society grows significantly (more committee members generally equals more bureaucracy). It was also noted at the time that 5 officers resulted in a committee of 8 - whereas an odd total number has advantages.

The rules indicate that the committee size may be determined by majority vote at a society meeting (section 5.1.i).

Also, the committee has the power to delegate responsibility and co-opt members as it sees fit (section 8.1.v).

**Comment by Unfocused** [comment]
Also: If we do have an even number on the committee, and we come to a stalemate, the president gets a 2nd vote - so we're covered either way (section 8.3, plus a couple of other sections for minor variations).

**Comment by Unfocused** [comment]
@phenomnomnominal, @jenofdoom, @Kevnz, @buildmaster, @vimto, @grahamjenson - could each of you provide a short bio/blurb/whatever. Just something to give people context as to why you think you should be voted in.

**Comment by jenofdoom** [comment]
I'm Jen. I'm a front end dev by trade, so I write JS for a living and have done so for quite a few years now. I also run training sessions to teach JS, both as part of my job, and for Catalyst's Open Source Academy and Summer of Tech.

I'm interested in being a part of the JS NZ society in order to help foster an inclusive and welcoming community. I'm also keen to be involved in creating a national grass roots JS conference (what do I mean by that? Broadly speaking, sub ~$100 cost tickets, even lower cost student/unwaged tickets, local speakers, rotating location between cities, code sprints etc).

I am also presently the Vice President of the New Zealand Python User Group, and I was the director of the national Python conference, Kiwi PyCon, in 2014.

**Comment by buildmaster** [comment]
Hi I'm Owen, Co-Founder and CTO of Hoist in my full time (a platform built on Node.js so I'm heavily invested in the future of JavaScript) 

I also run WDCNZ one of the bigger web dev conferences in New Zealand.

I've been on the board for Hoist, and helped on the committee of Summer of Tech while we founded that and got it off the ground. 

I love the idea of the Javascript Society and want to see it do well for the community. I also think I'm good at helping out committees with things that need to get done and my skills are pretty wide ranging from helping with accounts, to comms, to tech, to events.

**Comment by phenomnomnominal** [comment]
Hi, I'm Craig, I'm a developer working at Trade Me, where I spend all my time writing pretty big JavaScript apps. I'm a passionate supporter of all things JavaScript and this society seems to be the perfect vehicle to use that to build and grow the JavaScript community within NZ.

I don't really have any experience, but I've already learned a heap by being involved over the last year and am keen to continue being involved in any way that I can!

**Comment by grahamjenson** [comment]
Hi, I'm Graham. I am a developer at LoyaltyNZ (Flybuys) and currently working full-time building NodeJS services. I like Javascript both on the server in NodeJS and in the browser for the front-end apps. I am currently an organiser of NodeJS Wellington meetup and I would like to extend my involvement in the Javascript community nationwide through the JavascriptNZ Society because I like providing a place for people who are interested in technology to meet and talk about it, and for people to share what they have learnt and built as well.

**Comment by Kevnz** [comment]
Hi, I'm Kevin, I am the web platform developer for InSpark Technologies a medical startup. I have 15+ years of professional web development experience and despite numerous server side languages the one constant has been my love of JavaScript. I've done dedicated Front End development or a combination of both FE and node.js backed and am currently working on full stack JS project and even looking at JS on mobile. Put simply I love me some JavaScript. In addition work, I regularly speak at user groups and conferences on JavaScript. I also help organize both the Auckland JS meetup and the Auckland Node.js meetup and have helped facilitate better coordination between various tech meetups in Auckland to aid in the search of sponsors and hosting facilities and prevent date clashes. I love the idea behind the Society to help coordinate efforts nationally and bring people together in a safe environment to foster and encourage their JavaScript experience.

**Comment by vimto** [comment]
I'm Vim, Co-Founder and CTO of Atomic, a local startup that uses JavaScript
throughout it's tech stack. I also co-run Wellington.js.

I'm a big fan of Javascript. It's something I've used thorughout my
programming career, and I think it's a great language for newcomers and
professionals alike.

Given the increasing reach of JavaScript, and the many places it's used,
(as seen by the variety of JS-related meetups), I think a JavaScript
society is a great idea. Both as a way to encourage collaboration amongst
these groups (sharing resources, organising and promoting events, etc); and
as community in it's own right, with an annual event.

I'm happy to pitch in wherever I can, and have a bunch of experience both
technical and organisational to do so.

**Comment by jenofdoom** [comment]
Vote to expand the number of general committee members for 5 to 6 taken at AGM - +8 in favour

**Comment by jenofdoom** [comment]
Vote for Jen Zajac to be a committee member was taken at AGM: +11 in favour

Vote for Craig Spence to be a committee member was taken at AGM: +8 in favour

Vote for Graham Jenson to be a commitee member was taken at AGM: +9 in favour

Vote for Kevin Isom to be a committee member was taken at AGM: +9

Vote for Vim to be a committee member was taken at AGM: +8

Vote for Owen Evans to be a committee member was taken at AGM: +9
