### ISSUE TITLE
Enshrine an anti harrassment policy into law

### ISSUE THREAD

**Issue by faceleg** [JavaScript-NZ/Society-Meetings#14]
As suggested by @Unfocused, the [Geek Feminism Conference anti-harassment/Policy](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy) should be adopted and made law.

`Conference` should be replaced with `JavaScript New Zealand Society`.

Other portions of the policy should be left intact.

**Comment by Unfocused** [comment]
While we can adopt that one policy for both the society and it's conferences, it has a sister policy specifically written for communities:
 http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy 

I recommend we adopt both policies.

(Also, apologies for not sorting this out sooner - I started doing this in October last year, and never got around to finalising it)

**Comment by Unfocused** [comment]
Draft: https://github.com/JavaScript-NZ/Society-Documentation/pull/14

**Comment by Unfocused** [comment]
I think we'll be sorting this out in the next committee meeting, rather than the AGM. Having the committee implement it as a bylaw seems like the best approach (ie, this is something we need, not something we we want to vote in/vote out).

**Comment by widged** [comment]
Quick reaction. "If a participant engages in harassing behaviour, the Committee may take any action they deem appropriate, up to [...] identification of the participant as a harasser to other JavaScript NZ Inc members or the general public.".  

A google search indicates that it does appears in a few code of conduct. Apparently, it is deemed useful "when a community has an informal or undocumented structure, such that there is no central authority who can enforce anti-harassment norms."

A priori, I would presume that you always have the right to expel. Morally and legally (I am not a lawyer).  That you have a very low opinion of the harasser doesn't really give you the right to publicly tarnish his reputation. Morally and, importantly, legally  (I am not a lawyer). This would actually expose yourself and/or the victim to being sued for defamation. Then there is the issue that publicly shaming the harasser might actually put the victim at risk. If the harasser has a psychopathic type of personality, then the more you humiliate him, the more he might seek revenge for it... and that will done behind doors, where you can do nothing to protect the victim. 

More food for thoughts at [name and shame](http://geekfeminism.wikia.com/wiki/Name_and_shame) and [silencing tactic](http://geekfeminism.wikia.com/wiki/SLAPP).

**Comment by jenofdoom** [comment]
I actually think the topmost action is not public identification anyhow - it's raising the issue(s) with the NZ Police. So might be simple to switch that in instead? Anyone have any thoughts on that?

Rewritten version would be:

"If a participant engages in harassing behavior, the Committee may take any action they deem appropriate, up to and including expulsion from all JavaScript NZ Inc spaces and referral of the matter to the New Zealand Police force."

**Comment by phenomnomnominal** [comment]
That's a much better alternative, and it seems like it would _actually_ be a deterrent. Does that rewrite actually preclude us (or future committees) from naming and shaming? Because I don't personally feel like that would ever be the right action.

**Comment by jenofdoom** [comment]
I don't think it would preclude it, and I don't think we should write down that we would preclude it. While it's a dangerous and potentially controversial/harmful thing to do, as @widged alludes to, I can think of scenarios where it might be necessary (fortunately most of those are worst case scenarios that hopefully would never eventuate, but still). I think that removing it from the code of conduct de-emphasises it as part of our toolkit.

**Comment by Unfocused** [comment]
Ok, have updated that, using @jenofdoom's phrasing (ty!). That also ends up fitting with the last section of the conference CoC:

```
As a general rule, conference staff should not make any public statements about the behaviour of individual people during or after the conference.
```

**Comment by buildmaster** [comment]
merge in code of conduct please.

**Comment by Unfocused** [comment]
Community Code of Conduct: https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Community_Code_of_Conduct.md
Conference Code of Conduct: https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Conference_Code_of_Conduct.md
