### ISSUE TITLE
Lock down a logo for the society

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#16]
We've had a few designs presented to us by @jarred, they have been presented on slack and comments have been made. Not quite sure the best way to cast votes, open to ideas

**Comment by PrototypeAlex** [comment]
<img width="858" alt="screen shot 2015-09-04 at 3 53 31 pm" src="https://cloud.githubusercontent.com/assets/666638/9676269/1e674902-531d-11e5-8488-68d5a4a49692.png">
<img width="945" alt="screen shot 2015-09-04 at 3 53 44 pm" src="https://cloud.githubusercontent.com/assets/666638/9676272/234f7282-531d-11e5-912e-b29ca3d015c8.png">

**Comment by buildmaster** [comment]
A week before we create a channel in slack, post each logo as a message, everyone puts a reaction gif next to the one they like the most?

**Comment by PrototypeAlex** [comment]
:+1: @buildmaster, good idea, I can handle that.

**Comment by wrumsby** [comment]
![](https://pbs.twimg.com/media/COIvOqvWUAA2LCB.jpg)

**Comment by wrumsby** [comment]
As per vote on Slack, the following is the logo - https://slack-files.com/T09HZENRK-F0BFN4K3R-ccfaab373c
