### ISSUE TITLE
When Opening Nominations

### ISSUE THREAD

**Issue by chilts** [JavaScript-NZ/Society-Meetings#18]
Just a little suggestion. When opening issues for nominations and votes for the society positions, it's probably a good idea not to put the 'opening' and a 'nomination' in the same message. Yes, it's a small society and most probably the same people will be voted in, but probably best to separate the two (even if only by a separate comment).

e.g. https://github.com/JavaScript-NZ/Society-Meetings/issues/10, https://github.com/JavaScript-NZ/Society-Meetings/issues/11, https://github.com/JavaScript-NZ/Society-Meetings/issues/12. 

Probably better if like https://github.com/JavaScript-NZ/Society-Meetings/issues/9 and https://github.com/JavaScript-NZ/Society-Meetings/issues/13.

Just my thoughts for next time.

**Comment by PrototypeAlex** [comment]
yep, I agree with this, makes it a bit bias otherwise.

**Comment by chilts** [comment]
Cool.

**Comment by Unfocused** [comment]
Ugh forgot to comment here. Yep, agreed also. I'm going to document a checklist for preparing for an AGM - reopening/assigning this issue to ensure I include it.
