### ISSUE TITLE
Call for help with running NodeBots in other cities

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#19]
Need some people to come forward to run events in other cities, everything is setup, just need some event coordinators and wranglers.

**Comment by buildmaster** [comment]
@PrototypeAlex did this get done?

**Comment by PrototypeAlex** [comment]
It's got momentum, I'll post some notes on it soon.

**Comment by PrototypeAlex** [comment]
We now have a massive amount of momentum in Wellington, with Elf Eldridge helping out with the running of events and auditing of the kit, this has allowed me to step back to focus on sponsorship and coordination of national events.

Jacob has been helping out running events in Auckland twice a year, and we're now in talks with the Auckland Enspiral dev academy, hopefully they can run regular events and start a secondary collection of equipment there.

All in all things are looking really good for NodeBots NZ, so I'm closing this issue for now.

If you're reading this and would like to help out, please contact me :D
