### ISSUE TITLE
Shared bank account for Meetups/Events

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#2]
I'd like to propose an idea to having a shared account for all meetups willing to join.

With the idea that sponsorship can all funnel into the js.nz account, and every city has a shared eftpos card to use, or file expense claims against if that's too tricky. 

The goal is to reduce the personal liability of having sponsorship money in peoples personal accounts, and to make finding sponsors easier.

Thoughts and discussion required :smile_cat:

**Comment by buildmaster** [comment]
so the onus here would be working out a budget for meetups and the priority around them
- Do you allow expenses per head or per meeting
- Expense claims are easier from a management/security POV than a shared card
- is the aim for big meetings or lots of smaller meetings spread out around the country
- we'd have to have some kind of policy so people know what is and isn't appropriate to claim for
- it's not a 0 overhead thing

I don't mind but want to make sure everyone is aware of the -ves as well as the +ves

**Comment by PrototypeAlex** [comment]
Good points @buildmaster, I'm hoping the positives outweigh the negatives when we flesh this out.

**Comment by Unfocused** [comment]
So, umm... 

![ANZ card](http://i.imgur.com/Q9s9oE8.png)

(I haven't done this... yet)

**Comment by wrumsby** [comment]
Most recent JS meetup we ran in Auckland cost about $350 to run for about 60 people we probably didn't have quite enough beer or food either.

Unsure we'd be in a position to completely cover the costs of running meetups given other plans (e.g. #1) but I'm keen to see what we could do to make it easier for organisers.

**Comment by jenofdoom** [comment]
Having a central organisation to help organise sponsorships would be another way of easing the burden on local organisers, without going as far a directly providing money.

**Comment by wrumsby** [comment]
Potentially local JS meetups can affiliate with the society and the society may then provide some funding support (e.g. to pay meetup.com fees).

We should try to get a list of all the JavaScript-related meetups in NZ who might want to be affiliated.

**Comment by wrumsby** [comment]
Another suggestion to consider later is to provide video recording capabilities for meetup talks.
