### ISSUE TITLE
JSNZ merchandise and swag

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#20]
Once we lock down the logo https://github.com/JavaScript-NZ/Society-Meetings/issues/16, we should look into ways to get our brand out there and possible make a bit of revenue to support other activities.

@veb mentioned doing a http://teespring.com campagin would be cool, and that he has some connections there, which could be handy; I had thought teespring would be awesome too.

Stickers could also be a winner, but we probably couldn't sell them, however, I'm happy donating some of the node.js meetup funds or NodeBots funds to getting some stickers printed. (Hexagonal if possible :stuck_out_tongue:)

Other thoughts and ideas are welcome :smile_cat:

**Comment by Kevnz** [comment]
@PrototypeAlex yeah, stickers would be great to give away at meetups, heck I'd be happy to donate some cash if needed for them. Also +1 on the teespring campaign.

**Comment by Unfocused** [comment]
Thinking about this, one thing I've disliked about many tech events having a tshirt not be optional. If we do do a tshirt (I think we should, FTR), we need to recognize that some (many?) people won't want it. And since tech events so often get this wrong: if we don't offer fitted womens sizing, we're better off not doing it at all.

**Comment by veb** [comment]
We can cater to everyone using Teespring. Even toddlers. I think Teespring
also does stickers, I've just asked Walker Williams (CEO). So your one
campaign, will allow a few sizes for men, women, etc. :-)

We can also offer promotion codes for campaigns too, if you didn't know
that.

**Comment by veb** [comment]
I don't disagree Blair... I got given XXXL at my last PyCon and I'm not ...
a big guy by any means. :P

**Comment by PrototypeAlex** [comment]
@Unfocused, I fully agree that it should be optional. Would just be a way for people to show support if they like t-shirts or like throwing stickers in places.

We're experimenting with socks at Atomic, nice socks, apparently $8 a pop, wonder if teespring could cater for that too :smile:

**Comment by Unfocused** [comment]
Hah, socks would be a nice change. I've previously pondered about cufflinks, but I'm not sure our logo would be very suitable for that.

**Comment by buildmaster** [comment]
can we close this for now?

**Comment by Kevnz** [comment]
@buildmaster I say close it. Probably want to reopen it nearer to the conference. That would seem like the best time to launch something like this.

**Comment by PrototypeAlex** [comment]
I second that @Kevnz, can be closed for now.

**Comment by PrototypeAlex** [comment]
Closing, can be reopened when the conference comes around next year.
