### ISSUE TITLE
Proposal to bring an accountant on for financial year 2015/2016

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#21]
So it turns out the accounting was tricky this time around for multiple reasons, I dunno what I would've done without @buildmaster! Big shout out to him for sussing things out.

During the way we thought we're approaching the point in where we need an account to make things easier.

So I'd like to propose bringing on an accountant to help out.

**Comment by PrototypeAlex** [comment]
Also, if this passes, we'd need to find an account, so we're open to friends and family, any accountants that could work for us for cheap :D 

Enspiral Accounting have offered $450 a year to do the accounting for the society.

**Comment by Unfocused** [comment]
I was just about to suggest we should get a quote or two. I know some accounting firms will give special rates for societies/non-profits (IIRC, this was the case with Enspiral).

**Comment by jenofdoom** [comment]
Or if we'd like to stick with something very web-based for ease of contact, my partner uses http://beany.biz/ and it has been working out well. Their non GST registered level is $495 annually.

**Comment by jenofdoom** [comment]
Update as per committee meeting 21/3/16: @buildmaster is meeting with an accountant from Enspiral tomorrow and will report back.

**Comment by buildmaster** [comment]
Closing, we have engaged Enspiral for accounting
