### ISSUE TITLE
Move financial year changeover to 1st April

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/Society-Meetings#23]
To aid with accounting

**Comment by jenofdoom** [comment]
Discussed at committee meeting 27-10-2015 - would like to proceed with the change, but require a vote from all members as it's a rules change for the society.

Next steps: 
- @buildmaster wording a communication to email out
- Once vote is resolved, @PrototypeAlex to sort out the accounting to make the change

**Comment by chilts** [comment]
+1 vote from me. Sounds like a good idea.

**Comment by jenofdoom** [comment]
This is now resolved, as per Alex's report to the 15/2/16 committee meeting
