### ISSUE TITLE
Define and ratify a method for voting and meeting quorum 

### ISSUE THREAD

**Issue by stevie-mayhew** [JavaScript-NZ/Society-Meetings#24]
It would be good to have this in the documentation for meetings and to understand how the process works.

I imagine that an easy way to do this would be to open a channel in slack for each meeting which members should join if they are going to be involved. This will make it easy to see what numbers we need for votes to pass. The voting process of thumbs up / down worked well.

**Comment by buildmaster** [comment]
I'm not sure we're going to get an answer to this yet, closing for now
