### ISSUE TITLE
Figure out what new NodeBots gear should be bought for 2016

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#25]
We have a set of 20 Sumobots and 4 Spark Core kits currently. We need to figure out what we think we'll want/need in 2016. This may be just maintaining the current kit, improving on it (wider wheels? more spare parts?), or expanding it.

**Comment by PrototypeAlex** [comment]
We've decided to repair and replace broken parts immediately, so I've just ordered more servos, bread boards and some antistatic bags for shipping.

After that we'll be putting it to the community on what to buy next, likely candiates are spheros and parrot ar drones.

Any ideas for what we should get should be thrown into the Slack #nodebots channel.

Other ideas are a 3d printer, node rockets gear (platform / rockets), node boats kit, hexapod gear, all amazing fun stuff!!! much excite!
