### ISSUE TITLE
Discuss whether NodeBots needs a curriculum (and how to make one)

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#27]
NodeBots is somewhat unstructured at the moment - as it expands to more cities and repeat (regular?) events in cities, it may make sense to have a set curriculum that can be referred to each time.

If we do decide this is wanted, we'll need to figure out how to make one. And someone to own it.

**Comment by Unfocused** [comment]
This also ties in with the possibility of running targeted events (adults, kids, developers, students).

**Comment by PrototypeAlex** [comment]
Two outcomes come about while discussing this item.

1: I'll be working with @kaiwhata (A lecturer at Vic Uni's Engineering dept), to build some resources for use at NodeBots, both by event organisers and attendees. We'll give progress updates on how this is coming along when we kick it off.

2: @jladuval made the point of the lack of fun hacking events such as NodeBots for adults/developers/students, compared to the amount of events run for kids. I tend to agree, despite my passion in teaching kids robotics, and so we'll be primarily focusing on adults/students for the next year at least.

This does not mean we won't be supporting others that teach kids, in fact I'll still be working with the likes of coder dojo, maker party, etc to help them use the kit we've been building to teach kids. It just wont be our primary focus.

We can reassess this decision later on down the track.
