### ISSUE TITLE
Start sourcing organisers for NodeBots events in more cities

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#28]
We need to decentralise this - more organisers for NodeBots events around the country. Who do we know?

**Comment by PrototypeAlex** [comment]
We couldn't really talk about this at the meeting, so it's still open. Keen to hear ideas on how we can muster up more peeps.

**Comment by PrototypeAlex** [comment]
We've got an informal sub-committee going on, Elf Eldridge is helping out running events while I handle a newborn baby for a bit, and @jlduval will continue to run Auckland events.

We've had a few bites for south island events, and I think traction will happen soon, I just can't push forward on that front for a while.

Closing this issue as it's semi resolved, I think it'll naturally grow as we grow older.
