### ISSUE TITLE
Can CHCH.JS have funding to fly an Ember Speaker down from Wellington for a Meetup?

### ISSUE THREAD

**Issue by anotheredward** [JavaScript-NZ/Society-Meetings#29]
I'm currently approaching Zoltan who has run a series of successful Ember.js Schools in Wellington about coming down to Christchurch and doing a talk for us next year.
http://www.meetup.com/Enspiral-Dev-Academy-Meetup/events/226074926/

Is this something the Javascript Society would consider funding?

**Comment by Unfocused** [comment]
I don't recall this type of thing being brought up before, so I've put it on the agenda for the [committee meeting next week](https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2015/Committee-2015-10-27.md).

Could you give us an estimate of a budget?

**Comment by anotheredward** [comment]
Return Flights from Wellington to Christchurch, booked well in advance, range from $90-$200.
We're happy to provide Zoltan with somewhere to sleep.

**Comment by zoltan-nz** [comment]
Hi. It is very kind. Thank you. :) But don't worry too much about it. We (with my partner) already planned, that we visit Christchurch for a long weekend, so when this meetup gonna happen (this year or next year), it is a good reason to dedicate a couple of days for Christchurch. And nothing else better as a compensation than spending an afternoon with a great javascript community like yours in Chch. ;)

**Comment by jenofdoom** [comment]
Thanks @szines that's very gracious of you.

Closing this issue as resolved - at the committee meeting 27-10-2015 we discussed if flying speakers would be something we could do more generally. It's not in the budget right now but we will  investigate again towards the end  of this financial  year (refer to minutes for some  further discussion).
