### ISSUE TITLE
Hiring an Accountant

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#3]
Sadly this needs to be done. Any recommendations?

Enspiral Account do deals for non-profits, I use them for my own company and they are very affordable.

**Comment by Unfocused** [comment]
Which I guess brings up the obvious questions:
- Why? (Not challenging the assertion, just wanting to record the specific reasons/benefits)
- What's the ballpark figure for doing that?
- How much can we actually afford?

**Comment by buildmaster** [comment]
a compliance accountant shouldn't be too expensive. We need to make sure we have a viable society first with repetitive income etc.

**Comment by PrototypeAlex** [comment]
Hmmm, I added this because I'm no accountant, and slightly scared I'll stuff something up and get us in trouble in the process. If we're willing to take that risk I guess we don't need one currently.

**Comment by jenofdoom** [comment]
Agree that we probably don't need this up front. If we decide we need it later, I recommend http://beany.biz (all online, NZ based) who do a $495 per year deal for non GST registered entities.

**Comment by wrumsby** [comment]
> Why?

My recollection was that it was [part of the society rules](https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Rules.md#200-assurance-on-the-financial-statements).

**Comment by wrumsby** [comment]
@buildmaster mentioned point 3 of the relevant society rule re: an accountant.

> No review or audit of the annual financial statements is required unless a review or audit is requested by 5% of the Members at any properly convened Society Meeting

This would be discussed at an AGM - i.e. that we don't want to hire an accountant because of revenue.

**Comment by buildmaster** [comment]
so a few things we should do:
I presume we have an IRD number for the society?
apply for income tax exemption: http://www.ird.govt.nz/business-income-tax/paying-tax/tax-rates/bit-taxrates-non-profittax.html
if we have an IRD number they should have written to the society with return details for income tax on last year.

**Comment by PrototypeAlex** [comment]
Cool, as far as I'm aware we've never been given an IRD number, which would explain why they never sent return details.

I'll ring them up tomorrow to suss it out and post what's going down here afterwards.
