### ISSUE TITLE
Corporate sponsorship for nz.js directly

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#30]
Are we open to accepting sponsorship from corporates?
Are we happy with the tax that comes with this?
If we are happy with it, what do they get out of it? 
Will the money from each sponsor go to specific things, or until the kitty like the membership money?

**Comment by PrototypeAlex** [comment]
Looks like it may be a dup of https://github.com/JavaScript-NZ/Society-Meetings/issues/6

**Comment by buildmaster** [comment]
can we close this one and handle both donations and sponsorship in #6?

**Comment by jenofdoom** [comment]
I was going to do it the other way around, but yes. I will put some notes from the meeting on the other ticket momentarily. Closing this one.
