### ISSUE TITLE
Decide how NodeBots should be governed/managed

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#31]
At the moment Alex handles everything - which has a very high [bus factor](https://en.wikipedia.org/wiki/Bus_factor). We should look at possibly forming a sub-committee (or something).

**Comment by PrototypeAlex** [comment]
We decided at the meeting that other people are happy to start running events individually, without me 😎.

I'm still going to take the lead on finding funding and purchasing/expensing the kit.

@kaiwhata and I will be working together to build some resources around how to run an event as an organiser, and how to build/hack as an attendee.

The choice of what we do and where we go will be driven by attendees of NodeBots. So at every event we'll be asking what we should do next.

@Maeur1 and @jladuval have raised their hands to help run events where possible, as well as anyone else interested.

This will take a huge load of my shoulders, and enable me to focus on obtaining sponsorship and keeping the kit in order, while also allowing NodeBots to grow in the direction chosen by the people who engage with us.

Again, if you have any further questions on this, raise another issue or chat to us in Slack (#nodebots)
