### ISSUE TITLE
Event proposals / Call for help 

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#32]
There have been multiple requests for NodeBots to attend various events, mainly in Wellington, some of which I can't make. Along side these events, there are also the regular events we should be keeping up with, which again are being requested by keen Nodebotantist.

Here is a rough list of events, they are all optional, if we don't find an organiser then they don't get run, a little sadness but no love lost.

November (Sometime - Wellington) - NodeBots official event (I might be able to run this one)
November (26th - Auckland) - NodeBots official event (@jladuval organising)
November (28th - Wellington) - Hour of Code @ Scotts College (Needs organiser)
December (28, 29, 30th - Wellington) National Library Holiday Science (Needs organiser) (Have offered to pay us $250 + cater for us + have a 3d printer for us to use)

Sometime (Christchurch)
Sometime (Dunedin)

**Comment by Unfocused** [comment]
I know a couple of groups down here in Dunedin that might like to do this, including a couple of CodeClubs. I had some interest a couple of months ago when I mentioned it to one group, but they weren't ready for it at the time. I need to reach out to them and some others.

**Comment by buildmaster** [comment]
I'd 
a) help and 
b) run some events with a couple of codeclubs out here in Upper Hutt

but I've never been to or seen a nodebots event and as such I have no idea what they look like

**Comment by buildmaster** [comment]
by which I mean, organiser training might be a good event to run

**Comment by PrototypeAlex** [comment]
Good point @buildmaster, I've had a few other people raise the same point, attending a normal nodebots day might be a good makeshift way to understand about nodebots. 

I don't mind doing a training event for organisers, but I'd have to plan it out in advance.

**Comment by rjmackay** [comment]
I'm happy to help out with a future Auckland (or Hamilton) event.. unfortunately I'm out of town for Nov 26th :(

**Comment by PrototypeAlex** [comment]
Some outcomes out of the meeting we had last night:

The next Wellington event is on the 21st of November, @kaiwhata, @Maeur1 and myself will be running this, I'll open up tickets for this soon.

The next Auckland event is on the 25th of November, @Kevnz and @jladuval will be running that, I think it's being announced on meetup.com?

We'll be running an organisers event (cc @buildmaster) on the 5th of December, where anyone keen on running an event themselves is free to drop in and learn what it's all about.

**Comment by PrototypeAlex** [comment]
@rjmackay we don't yet have anyone on the ground in Hamilton, if you wanna talk to @Kevnz and @jladuval I'm sure they'll give you the run down, alternatively I can open up the organisers event to remote attendees, which should achieve the same thing :D

**Comment by PrototypeAlex** [comment]
Closing for now, if you have anything further to add on this either raise a new issue, or just yell at me on slack (#nodebots).
