### ISSUE TITLE
Sourcing video recording capabilities for meetups

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#33]
Could possibly be talked over on Slack, but might be good on here to have some official threads to be discussed in the next meeting. 

Ideally, the society could own some gear, that meetups could share between each other, which means we'll probably need multiple sets to be fair?

I've tried a cannon 5d with rode videomic and it's not good, the FAT32 memory doesn't allow for a recording longer than 11 mins hidef, or 26 minutes 480p.

I've also tried a logitech webcam and a MXL AC-404 mic, which was also bad, the webcam was constantly refocusing when the speaker moved around because of the low light due to the projector.

Very keen to hear of setups that work well for recording meetups, so we have a better idea of what to get.

**Comment by buildmaster** [comment]
I have an old FLIP HD video camera, that might be useful and cheap. I don’t use it for much. I used to record my talks with it.

**Comment by jenofdoom** [comment]
Some workflow resources at http://code.timvideos.us/home/

NZPUG has invested in one of these https://www.youtube.com/watch?v=ma-1F7vQ4CQ but I think that's overkill for right now

**Comment by jenofdoom** [comment]
Resolved in committee meeting 09/12/15 that we should put together a proposal for some kit, so we have a $$$ figure to approve.

**Comment by vimto** [comment]
These were two pieces of audio-kit that were recommended by a sound engineer for our meeting room. We should have them in the Atomic offices in the next few weeks, so we could potentially test at the next Wellington NodeJS meet-up.
- [Focusrite 2i2 - in NZ $269](http://www.rockshop.co.nz/shop/focusrite-scarlett-2i2-2-in-2-out-usb2-0-audio-interface-featuring-2-focusrite-preamps.html)
- [Crown PCC 160 - $349 USD](http://www.sweetwater.com/store/detail/PCC160)

**Comment by phenomnomnominal** [comment]
So our live streaming set-up is some Vaddio gear that uses Lync and is probably out of our $$$ range. Still waiting to hear back about what we use for just straight recording.

**Comment by PrototypeAlex** [comment]
@phenomnomnominal at the committee meeting today, we decided that the money in the Wellington Node.js Meetup pool should be spent on the video gear, which means we have a budget of $570.00. (+- a little bit if need be, from the nodebots kitty)

Are you ok to continue the research with that budget in mind?

**Comment by phenomnomnominal** [comment]
Yep, absolutely.

**Comment by jenofdoom** [comment]
Update as per committee meeting 21/3/16 from @PrototypeAlex : We’ve purchased a lapel mic and mobile phone Tripod, thanks to @phenomnomnominal and everyone else for the recommendations. If this turns out to work we could probably buy a few per city as they are relatively cheap (170 per setup).
