### ISSUE TITLE
Facilitate meetups

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/Society-Meetings#34]
As discussed [in the committee meeting](https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2015/Committee-2015-10-27.md#29-flying-speakers-to-meetups), potentially there are things society could be doing to help local meetup organisers.

The main issues appear to be to be sponsorship and getting venues, but we probably need to seek further feedback,  and even start a conversation between the various organisers. It appears @Kevnz may have been doing some work in this space already.

**Comment by jenofdoom** [comment]
@Kevnz indicated he would be interested in taking on the role of usergroup facilitator at committee meeting 09/12/2015

**Comment by Kevnz** [comment]
Okay, I reached out to Wel and ChCh and they (ChCh) were interested in donating to the Society to have the society fly someone down to them for speaking. Is that a thing we can do? Haven't had a chance to follow up further as I've been busy and the holiday break.

**Comment by jenofdoom** [comment]
Update as per committee meeting 21/3/16: It sounds feasible to do this (where 'this' = run the Christchurch sponsorship through the society to enable the flights), @Kevnz to follow up.
