### ISSUE TITLE
Learning materials - How can we best handle these?

### ISSUE THREAD

**Issue by geordidearns** [JavaScript-NZ/Society-Meetings#38]
Hi all,

A brief discussion in the 'general' channel on slack has led to an issue that's worth discussing. @PrototypeAlex & Graham Jenson (among others I imagine) have kindly donated some books to the society, although we are trying to figure out a solid process around the lending/returning on the materials if we choose to take this route.

Potential issues we face:
- Organising the delivering/return flow
- Duration of lending
- Payment for courier for regional post (Is it an individual thing? or a society expense built into membership?)
- Location of books (Perhaps Enspiral Dev Academy?)

Other issues?

I have put my hand up to maintain the delivering/returning process if we can organise the other aspects :)

Thanks

**Comment by PrototypeAlex** [comment]
I think there are some great open source library loaning systems out there, might need a spike to look into them. But if we can find a good one that'll solve the first two problems.

In terms of the location of the books for their default state, I reckon Enspiral is the best fit, that way the students there can use them while studying.

We should raise the option of the society fronting the cost of shipping, but I think it'll likely be pushed onto the requester of the items, rather than through membership costs.

**Comment by jenofdoom** [comment]
Slightly off the wall suggestion (feel free to shoot down, I haven't really thought through all the implications yet) - perhaps rather than maintaining our own private libraries we should be pushing public libraries to buy in (or we could donate) books that we think would be beneficial. This has the side effect that we get books into more hands than just our own, plus they have established inter library loan mechanisms for moving stuff around?

**Comment by jenofdoom** [comment]
e.g. https://www.wcl.govt.nz/about/services/suggestion.html for Wellington region, I'm sure other regions have same mechanism

I guess this idea doesn't have to be mutually exclusive with a private library too :)

**Comment by annavlz** [comment]
Wellington libraries are not included into the Smart-libraries system. I (in Lower Hutt, or other people from greater Wellington) can't borrow books from Wellington library for free, but I can have books from Porirua, Kapiti, WelTech and even Masterton! 
Libraries also have a decent amount of bureaucracy. 
If we want to make books available to people who might be interested in them, we need to think who these people are. We have Uni students (with a lot of resources and support of their own) and self-learning people (some of them don't have access to Wellington library). These people if they are active and willing to learn will end up at EDA earlier or later, even if not studying then at some meetup.  
Another plus to EDA - minimum bureaucracy)))

**Comment by widged** [comment]
What about ebooks? I have a huge collection of them. But it is not always clear how you can lend them to others. The Wellington library, for instance, has that system that you can only borrow e-books if nobody else has borrowed them when you do (apply the same model as for physical books).

**Comment by PrototypeAlex** [comment]
@jenofdoom @annavlz, I initially tried donating the books to the Wellington Library, I stopped short of calling old disconnected numbers, and numbers where no-one answered. The email I sent directed me to a phone number that was disconnected. 

So I put it in the too hard basket and offered people to take it off my hands on the slack channel. This caused a heap of people to say they'd be interested in the books, so we threw around some ideas of how we could get it to work on a scalable level.

The main problem with donating it to Wellington library, aside from the hurdles, is that it's hard to get access to the books outside of Wellington. Ideally the JS society members should have access to these books, they are all JS specific, and very good books.

The only downside is the books aren't publicly accessible outside of the society. But then again, they are all pretty low level books, not really what I'd call entry level.

Happy to donate them to the Library if that's what we consider the best thing to do, but it seems the EDA would be a better place to donate them regardless of if we setup a sharing system.

Thoughts?

**Comment by PrototypeAlex** [comment]
@widged, interesting thought on the ebook idea. I've no idea how that would work, but it'd be awesome if we could get it to work :D

**Comment by michael-smith-nz** [comment]
We'd be happy to host the library at Enspiral Dev Academy in Wellington if we decide on this. With @geordidearns being a grad and putting his hand up to maintain the delivering/returning process this could work quite well.

**Comment by widged** [comment]
@PrototypeAlex re donating. When I asked my neighbour who works for my local library, she told me that they only accept books from authorised sources.  What you can do is what @jenofdoom  suggested, make a recommendation for them to buy the book. If you go the central library, you can ask for a form for that.

**Comment by jenofdoom** [comment]
@PrototypeAlex aha, yep that totally makes sense. in that case +1 for eda library, if they'd be on board with that

**Comment by geordidearns** [comment]
@PrototypeAlex - What are the next steps for moving this forward do you think? I'm keen to not have this fade into the mist of a github issue haha

**Comment by PrototypeAlex** [comment]
@geordidearns have you talked to the EDA, are the keen to be the Library? if so then we just need to suggest the software to handle management, name some librarians and Bob's your mothers brother.

We'll need to raise this a a committee meeting, to make sure the society is on board with helping out and supporting it.

**Comment by jenofdoom** [comment]
Update as per committee meeting 21/3/16: Briefly discussed the shared library idea, no dissenting opinions from us, sounds like a great idea!

**Comment by veb** [comment]
I wonder if we can incorporate this into the version 2 website for JSNZ: https://github.com/JavaScript-NZ/Society-Meetings/issues/39

Should be relatively easy inside a membership only part of the site.

**Comment by buildmaster** [comment]
is this sorted yet? can we close the issue?

**Comment by PrototypeAlex** [comment]
@buildmaster Nope, not yet sorted, I still have a heap of books sitting at my house gathering dust.

@veb's idea sound awesome, but we'd still need a central place for the books to be kept, either that or mini libraries at each City, which might be a bit easier, but would then require some management software to keep track of everything.

@geordidearns if you'd still like to champion this, we could meet at some stage and chat about what we need to do to propose a solution to the society.

**Comment by geordidearns** [comment]
@PrototypeAlex  @buildmaster - I have previously spoken to Joshua Vial about hosting them at Enspiral dev academy, they were keen! (It would also open up the society to EDA students as they are working off a full javascript curriculum now i'm pretty sure?) - What I imagine we need to do is organise the lending etc... I'm unsure about how to go about it..but i'm sure we can work something out!

**Comment by jenofdoom** [comment]
Discussed at committee meeting 19/03/19 - we think they are successfully housed at EDA now.
