### ISSUE TITLE
Membership access

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#4]
How do we allow people to join us as paid members?

Initially I was thinking teespring would be an easy win, plus tshirts \o/

Another way would be if finish off the work that @Unfocused and myself started with getting the website up and running with a paypal setup in there (it was mostly @Unfocused that did that work, I just wired up the paypal stuff).

**Comment by jenofdoom** [comment]
A third option is a dedicated membership management solution like e.g. Wild Apricot http://www.wildapricot.com/ or Nation Builder http://nationbuilder.com/

Pros of these: makes it really easy to handle all the compliance stuff for having members, makes it really easy to ask people to renew annually, have a bunch of extra features for e.g. running events.

Cons: can be a bit awkward to bolt onto the side of a website, costs $$$

NZPUG have been using Wild Apricot for about two years now. It's made all the membership management stuff dead easy, and we ran ticket sales for Kiwi PyCon from it. It integrates with a paypal account. However it just got more expensive so we're probably going to switch in the near future.

**Comment by Unfocused** [comment]
TBH, I _really_ hated WildApricot. I had looked into & trialed WildApricot and a few others last year - they seemed to have some utility, but most were just kinda awful. Generally all just felt like more work to use them than not. And they all aim to do everything and try their best to lock you in (with no decent APIs). 

The one exception I remember is NationBuilder, which even has a good supported API. But it would end up being just under $500/year :( I guess one option is for a few of us to eat that cost ourselves, to bootstrap things (I'd be happy to contribute).

**Comment by wrumsby** [comment]
Consensus - registrations via email to society email address, send an invoice, $NZ 20 per person, once paid you are a member.

**Comment by wrumsby** [comment]
- Set up an email address - e.g. `membership@javascript.org.nz` - @Unfocused 
- If this is ready by WDCNZ @buildmaster will announce this and we can have material at the conference
- @PrototypeAlex to set up https://buffer.com/ a/c

**Comment by Unfocused** [comment]
Er, forgot to mention here, `membership@javascript.org.nz` was setup not long after the meeting, and will deliver mail to the committee.
