### ISSUE TITLE
nz.js Sponsorship - What are we offering?

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#45]
While building the sponsorship proposal, I came to a brain blank of what we are offering as a society, to companies and individuals that want to sponsor the us.

So with that said, I'd like to use this issue as a brainstorming session, and whatever is discussed in here can be proposed at the next meeting, and hopefully adopted into the sponsorship proposal.

Some initial thoughts would be:

Logo placement on our soon to be deployed website (javascript.org.nz)
Offical badge created for the sponsor to place on any of their own marketing collateral? 

... and then my mind draws a blank

**Comment by PrototypeAlex** [comment]
Following on as an after thought, if we are able to purchase professional video gear for meetups (see https://github.com/JavaScript-NZ/Society-Meetings/issues/46 for more info), we could get a really nice intro piece created for the meetups, that contains our society sponsors logos.

**Comment by jamesmacfie** [comment]
What's out relationship with the Node and JS meetups? Like, if you're a sponsor and you're looking to hire JS devs then having your jobs posted at those events seems like gold to me.

**Comment by PrototypeAlex** [comment]
That's a good point @jamesmacfie, we could offer a flat budget to each js meetup based on how many attendees they have, and how much money we can raise.

The relationship between the meetup is still being discussed. I think @Kevnz has some ideas around it.

The only exception is the node.js meetup in Welly, which I run out of the society's accounts The sponsorship is still done manually for that meetup, and any sponsorship money raised goes into the society, where there is a node.js.wlg account there. Then we just collect receipts for any events, and pay that out of Xero as an expense. It's been working well, and doesn't create too much overhead, so I'd be interested to see what it's like rolling it out as an option to other meetups.

**Comment by PrototypeAlex** [comment]
Another interesting thought that sprang out of a conversation @aurynn and I had was, potentially, the sponsorship money could go to paying for a javascript community manager:

That is, someone who could be in charge of finding new speakers, running events|conferences|meetups, facilitating meetings, finding venues, recording the meetups.

Not sure how that would work across the country, but I think it's an interesting idea worth a discussion.

**Comment by buildmaster** [comment]
a) we need to separate the physical nature of sponsorship (taking the money, the value the sponsor gets) from the logistics of where that sponsor money goes. So we _can_ create tiers of sponsorships based on the value of the sponsorship itself.
b) as above we could say that each meetup paid through JS NZ gets up to 4 local sponsor slots through JS NZ (at $value each) then then there are up to 2 global sponsors at $value x 3 each) for example. We'd probably get buy in from Wellington, maybe Auckland and as we're an official entity we make it easier for groups to take money. 
c) We should take money for logos on anything that's unintrusive, yes to corporate membership, yes to sponsoring the society as a thing and having logos on web site.
d) if we split the sponsorships right down, people can take more or less sponsorship things as they see value etc.

**Comment by mexisme** [comment]
Perhaps you could style it similarly to how we did for DevOpsDaysNZ?
I.e. one of our main goals was to build and interconnect the DevOps community.

That includes things like making it easier for businesses to connect with prospective employees (not in a creepy stalker kind-of way, BTW) but more-importantly to help their employees keep abreast of fast-moving technology -- it's impossible to go on enough training to do this;  I'd argue this is what has helped drive the AWS meet-ups, too.

One other thing that we'd _really_ like to do is make stronger connections to other Tech communities, societies and meet-ups in NZ and globally, on the basis that we all have useful knowledge to share.

**Comment by PrototypeAlex** [comment]
@buildmaster I'm on board with the meetup sponsorship affiliation.

So with that said, the two main features, is branded advertising on our website, and branded advertising during affiliated meetups, Auckland? and Wellington to begin with, which could expand to more later. 

Is there anything else I missed, or other things that could be offered?

**Comment by buildmaster** [comment]
closing this as relates to last conference
