### ISSUE TITLE
nz.js Sponsorship - Sponsorship Levels

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#46]
We need to figure out what sponsorship levels we offer for the society, or if they are needed at all.

For other documents I've created, I normally offer 3-4 tiers, which works well for both small startups and larger companies.

Part of the problem is that the initial offering (https://github.com/JavaScript-NZ/Society-Meetings/issues/45) should dictate the levels of sponsorship, so at a base level, my initial thoughts would be:

Bronze: $1000
Silver: $2500
Gold: $5000

One or two sponsors at this level would allow us to do big things with Meetups, such as purchase professional recording equipment for meetups in major cities, maybe even pay someone to do video editing for each meetup (Maybe see if Devon want's to build us a nice video intro like he did for WDCNZ).

Keen to get peoples thoughts on this, and the linked issue.

Hopefully we can propose 3-4 tiers at the next meeting so we can get a sponsorship document out the following month.

**Comment by buildmaster** [comment]
closing this as relates to last conference
