### ISSUE TITLE
Create a Tech Community Heroes award

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#49]
It'd be great to have a way to congratulate people in our community, and others, that's decoupled from working for a successful company, or contributing to open-source projects (although that could well be encompassed here?)

@ootoovak pointed me towards Ruby Heroes, which looks like a great initative - (see this - behind a broken ssl site, it's legit though, I swear 😅 - https://railsgirlssummerofcode.org/blog/2016-06-01-ruby-heroes-2016)

I'm unsure if we should do it as a JS Heroes, or if we should get other groups involved and make it larger than just JavaScript itself. Easy targets would be getting the Py people, PHP group and the Ruby society involved, I'm sure there's other groups that would jump on board too.

Would love some thoughts and feedback.

**Comment by timmy-wright** [comment]
Hey,

This is a great idea. There are lots of little tech communities around that could be interested too - scala, grovy, go, rust, etc. 

If you go the multi-group way then it might be sensible getting a larger technology organisation involved - like NZCS or IEEE (both of whom have changed their names in the last few years - no idea what they're called now). But then you have to deal with their politics, so might not be worth the overhead of engagement.

**Comment by buildmaster** [comment]
a) what do we want to give as an award, is it just kudos? is it monetary? is it other things (we could have some sponsorship swag for the hero, like a years free membership to x y or z)
b) need to make sure it doesn't become an insular group, therefor I'm against academy style "winners of awards become the people who vote on the award winners" we need to make sure it's inclusive
c) it needs to mean something so tying it in with an event that already has people there is good. Making sure that nominees can attend though is important (sponsor their ticket and travel?)

**Comment by timmy-wright** [comment]
Is another way approach to find out about other awards and make an effort to nominate people for those awards?

**Comment by PrototypeAlex** [comment]
@buildmaster 

a) I'd love to see kudos, or something like a trophy (I don't think we have enough trophies in tech)
b) Totally agree, I wasn't a fan of how the Ruby community in the states do it.
c) Yes, and sponsorship would be awesome if we could pull it off.

I like what @drtimwright said, we could just steal the categories that the other older communities have, thinking up our own ones might take a while, but not impossible.

**Comment by PrototypeAlex** [comment]
Done, big thanks to @annavlz for pushing this through to the end.

Looks kind've suspect that I created the issue and won the award 😁.
I swear it wasn't rigged...
