### ISSUE TITLE
GST Registration

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#51]
Due to a recent forecast for the society's financials, it would appear we will soon break the 60k limit that applies pre GST registration, this will likely happen during ticket sales for the conference, so we should be proactive about this and add a GST cost to the tickets, and register for a GST number ASAP.

@jenofdoom and I have confirmed with accountants that nothing retroactive needs to happen, once we obtain a GST number GST will be paid from that point on, so we're safe from any previous income generated being taxed.

So with that said, we just need to pass the motion to register for GST.

**Comment by buildmaster** [comment]
As this becomes a compliance issue I wouldn't imagine this has to go to a full vote. We need to be able to vote on these things out of band. Perhaps just using this github issue to gather votes?

**Comment by buildmaster** [comment]
👍 from me and we have to charge GST from the moment we're registered. @jenofdoom @PrototypeAlex are there any outstanding sponsorship invoices?

**Comment by PrototypeAlex** [comment]
Yes, one from Talent Army for the Wellington JavaScript meetup. Will this need GST applied to it @buildmaster?

**Comment by buildmaster** [comment]
have to take accountant advice on that. I'm unsure if it's issuing date or payment date that applies.

**Comment by phenomnomnominal** [comment]
It should just be as simple as filling out [this form](http://www.ird.govt.nz/resources/2/d/2d6150804ba3960294d3bd9ef8e4b077/ir596.PDF)?

**Comment by PrototypeAlex** [comment]
@phenomnomnominal LOL, simple and IRD.

**Comment by jenofdoom** [comment]
+1 from me on going ahead with this ASAP (although as @buildmaster says we should take advice re: outstanding invoice)

I have been invited to the Strip beta so I am setting that up for the society to use for the ticket sales. I'm working through the setup process for that but I'm close to being ready - so I'm keen to get a move on the GST number so I can bake that into ticket prices.

According to http://www.ird.govt.nz/gst/gst-registering/register-who/ we must register within 21 days of me starting to 'sell' stuff with GST as a component. Although they contradict that a bit and also say "You can only charge GST on your sales and income and claim it back on purchases and expenses if you're GST registered."

Apparently there is also an online process for getting the number http://www.ird.govt.nz/online-services/service-name/services-g/online-gst-registration.html but TBH it looks a bit complicated and I think we might want to get the accountant to do it on our behalf?

**Comment by buildmaster** [comment]
having just done GST registration with WDCNZ it wasn't very difficult. It's a pretty simple form.

**Comment by buildmaster** [comment]
And you can't put a GST on an invoice without a GST number, so I think the 21 days are that you can issue and receive GST free sales up to 21 days after GST registration.

**Comment by PrototypeAlex** [comment]
Ok, I think we have majority of the committee members, so unless I hear otherwise, I'll file the form for GST registration tonight.

**Comment by buildmaster** [comment]
can we try and get an answer on the outstanding invoice first? We may be able just to reissue invoice with GST attached and make it simple?

**Comment by buildmaster** [comment]
Registration is now done
