### ISSUE TITLE
Membership Fee

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#52]
So we have a conference coming up and we're getting more settled on who we are as a society (although there's much more we should and could be doing I'm sure we all agree)

But we need to address membership fees and meaning.

Currently the rates were set at a one off for $20 to help us get started. We hope that we conveyed there would be no sense of "lifetime membership" around this and we've often spoken about making it a true recurring levy

Now that the society is GST registered the fee, by necessity, has to contain a GST component. We need to ensure that the GST inclusive price is both affordable for as many as possible, ensures enough income for us to not go broke as a society.

We'd like to solicit feedback (as we have before) on the following

- Would you be comfortable with a recurring membership fee
- if so or of not what would you want from a membership fee that was recurring
- What would be a realistically affordable price point and what should qualify as a discount or free membership [$25, $30, $40, more?, less?]

**Comment by mogest** [comment]
$35/year incl GST seems like a nice price point.  How about allowing people to pay any multiple of $35, and the extra can go towards sponsoring members for whom $35 is a dent in their budget?  I feel like quite a few people would be happy to pay $70/year if they knew they were bringing another person into the society.

**Comment by timmy-wright** [comment]
Most societies have recurring membership fees - I actually assumed that the $20 was a recurring one! $3 per month makes $36 per year - so perhaps that is a good point as it's "cheaper than a coffee every month"?

(although actually collecting the money per month would likely be too much overhead).

Tim

**Comment by jamesmacfie** [comment]
I feel like it should be as cheap as it can be without making the society struggle. That hasn't come up at the $20 price point so increasing it to $25 (to round things off) to deal with GST sounds reasonable to me.

I do like the idea that @mogest proposed of opting to pay more if you can so we can get others into the society who would normally not be able to.

**Comment by bas-ie** [comment]
Agree with @mogest, $35 recurring. I also think you might get a few people willing to pay "life memberships" in order not to have to deal with recurring payments, not sure how much those would be though. Companies might be willing to pay an annual fee and expense it to get their employees involved.

**Comment by PapaBearNZ** [comment]
Another +1 for the $35 price point.  Not too much.  Not too little.

**Comment by timmy-wright** [comment]
What do similar societies charge?

* OWASP charges $50US per year. https://www.owasp.org/index.php/Membership - they are much bigger than us :)

Actually, that's the only example I could find with limited googling time available :)

**Comment by jenofdoom** [comment]
NZPUG (the Python society) charges $25 IIRC

**Comment by faceleg** [comment]
+1 for $35 per year

**Comment by stevie-mayhew** [comment]
+1 for $35 per year and I also like the "pay more and allow others to use that fund" idea that has been brought up

**Comment by PrototypeAlex** [comment]
The majority seems to be in favour of $35 per annum, so I'll propose this in the committee meeting tonight and see how we go.

**Comment by timmy-wright** [comment]
$35/year also means the society might have some surplus funds to give reduced membership to those that have greater financial constraints.

**Comment by PrototypeAlex** [comment]
This was discussed in our Jan committee meeting and the outcome was noted: https://github.com/JavaScript-NZ/Society-Meetings/issues/52

**Comment by timmy-wright** [comment]
@PrototypeAlex : what was the outcome?

**Comment by PrototypeAlex** [comment]
ha, whoops, linked the wrong thing here, was trying to link to the minutes: https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2017/Committee-2017-01-22.md#membership-fee-52
