### ISSUE TITLE
Setting up the society as a charity

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#53]
@jenofdoom and I have been having some discussions about the potential to switch to a non-profit while we've been working on the nz.js conference, and I thought it'd be a good time to start the discussion here too.

@buildmaster had some valid points, as he was involved with the Summer of Tech change from a normal society to a non-profit.

Anyone else have thoughts or pointers on this?

**Comment by buildmaster** [comment]
Not for profit or charity? Not for profit doesn't get us much. We're currently a company not for profit. Charity overhead is pretty heavy.

**Comment by PrototypeAlex** [comment]
Ahh, my bad, Charity. Will change the title

**Comment by PrototypeAlex** [comment]
Closed, we spoke about bringing this up again at a much later stage.
