### ISSUE TITLE
Membership - Reoccurring subscriptions

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#54]
With the upcoming conference, it's probably a good time to setup automated an subscription to the society.

@jenofdoom has landed us a stripe account, and they support reoccurring payments, with a really nice API, so this combo might enable us to do something from the new website.

**Comment by jamesmacfie** [comment]
Awesome - this should be relatively easy to integrate with KeyStone. Will need to also be integrated with Xero as well

**Comment by PrototypeAlex** [comment]
@jamesmacfie what's the deal with this, I see emails come through now, do I need to invoice out those people, or is it going straight to stripe?

Sorry, I should've asked this when I saw the first one.

**Comment by jamesmacfie** [comment]
Sorry, @PrototypeAlex, if you could fire off the invoices for these then that'd be great. Haven't got the subscription stuff up yet.

**Comment by buildmaster** [comment]
I'll send them out now

**Comment by PrototypeAlex** [comment]
The outcome of the last committee meeting stated that we're going to implement this through Stripe inside our keystone.js site. (https://github.com/JavaScript-NZ/Society-Meetings/issues/54)

@jamesmacfie will be on point.

**Comment by PrototypeAlex** [comment]
Whoops, wrong link, try this one on for size: https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2017/Committee-2017-01-22.md#subscription-system-54

**Comment by stevie-mayhew** [comment]
@jamesmacfie this should be good to close now?

**Comment by jamesmacfie** [comment]
Good to close
