### ISSUE TITLE
Next year's conference

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/Society-Meetings#55]
I'm certainly going to have more bandwidth to think about it after this year's conference, but I wanted to at least jot down a few points for discussion.

When I initially was thinking about the conference, one of the key planks of my proposal was that we rotate between different cities (see [issue 35](https://github.com/JavaScript-NZ/Society-Meetings/issues/35)). It fits in with one of my core drivers for the conference - affordability and accessibility - in that we expose the conference to a rotating set of 'locals' and local students.

An obvious downside is that you need to engage with different conference runners every year - but on the other hand organising doesn't become such a huge drag / stress generator as a particular local team only gets tapped every 3 or 4 years. With the nz.js(); committee as a steering board, and previous runners available for advice and guidance, we could make the event more resilient and sustainable over a number of years. I know this format _is_ achievable because Kiwi PyCon does it (Christchurch -> Dunedin -> Auckland -> Wellington).

My suggested would be that we'd look to get interested core teams to submit proposals. It would obviously be a boost to be able to have the outline of a process in place by the conference so we could announce it during the closing.

Anyhow this is just my initial thoughts, keen to hear what others think.

**Comment by PrototypeAlex** [comment]
I was at first hesitant on rotating cities, thinking that if we wanted to emulate the success of Kiwicon or Webstock, we'd have to base it in one city.

But after you spoke about the reasons for doing so in your closing @jenofdoom, I agree, we should rotate it so we can get more people attending that wouldn't normally be able to. 

Even speaking as someone who isn't financially constrained, I couldn't make it to Auckland easily for a conference, due to family constraints. So I'd imagine others, either financially constrained, time poor, unable to be away from their family, or anyone less mobile, would struggle to attend a conference outside of their home city.

So I agree, we should rotate it if possible.

That said, If I'm not treasurer for the upcoming event, I would be in a position to help run one, and would be able to assist anyone looking to champion the next nz.js(con).

**Comment by jenofdoom** [comment]
As per committee meeting on 2/4, we will proceed with an application process for potential interested conference runners. The deadline for applications is the __23rd of April__.

* Learn about what's involved in running an nz.js(con);  with our [detailed conference runner's guide](https://github.com/JavaScript-NZ/nzjscon-docs)
* [Apply to run nz.js(con); 2018](https://goo.gl/forms/9O6bt3gXXRuI2FGQ2)

If you have any questions about the process, ask here! Or pop the committee an email at [committee@javascript.org.nz](mailto:committee@javascript.org.nz).

**Comment by shearichard** [comment]
On the subject of where/when for future conferences there is, I believe, an argument to be made for running it over a weekend. 

There are, I assume, people who might wish to come but can't easily take off time from work or persuade work to allow them to come on work time. 

I appreciate there are others for whom a weekend would be less convenient (or who quite enjoy having two days out of the office on the company ticket ;-) . 

Anyway just a thought.

**Comment by jenofdoom** [comment]
Hi @shearichard, see https://github.com/JavaScript-NZ/nzjscon-docs#two-days-during-the-week :)

**Comment by richard-lopes** [comment]
Hi ladies, gentlemen,
I recently joined NZ JS and happy to help with anything regarding conferences.
I am coming late to the party to fill the April form and I was wondering what were the results of this survey.

**Comment by jenofdoom** [comment]
Hi @richard-lopes! Since this ticket was last commented on, we've made some progress. @stevie-mayhew is directing the 2018 conference in Auckland. Dates are still TBD. If you're interested in pitching in, there is a [#conference](https://javascriptnewzealand.slack.com/messages/C65UCNAN6/) channel in [our Slack group](http://slack.javascript.org.nz/).

I'm going to close this ticket for now, but for others reading this, you can join the channel mentioned above or keep an eye on [the society website](https://javascript.org.nz/) for an announcement.
