### ISSUE TITLE
Should we as a society be neutral on matters?

### ISSUE THREAD

**Issue by Kevnz** [JavaScript-NZ/Society-Meetings#56]
This is a fairly complicated issue. @PrototypeAlex made a comment on twitter after accidentally tweeting from the wrong account. In the [tweet](https://twitter.com/PrototypeAlex/status/837916073110360064) he said JSNZ is neutral so I asked but should we? He suggested an issue and as @phenomnomnominal pointed out in the same twitter thread, it's tricky.

I know we have a code of conduct that we expect both members and sponsors to agree too, but should we take a stand and speak out (as a society) on things industry related?

**Comment by PrototypeAlex** [comment]
For context to those that don't have Twitter:

At around 7:30pm on Saturday (4th March) I retweeted this tweet, from the JavaScriptNZ account:
https://twitter.com/nrrrdcore/status/837829044699717632

Once I'd figured out I was on the wrong account, I followed up on my own account: https://twitter.com/prototypealex/status/837916073110360064

**Comment by PrototypeAlex** [comment]
Personally, I think the society shouldn't have an opinion on these matters, and if we were it'd have to be the collective opinion of all our members.

That said, it does become a problem when companies like Uber and Palantir offer sponsorship. After going through an issue recently I wonder if we need to better define our sponsorship criteria.

However I'd love an open to discussion about the neutrality of the society, as we might figure some things out in the process.

@phenomnomnominal and @grahamjenson have already pointed out on twitter, that it's a hard line to draw, transitive blame on such matters is tricky, and context of evil doing opaque. Which sum up my thoughts well.

**Comment by jenofdoom** [comment]
I 100% agree that we should not be neutral, but if we are taking positions they have to be on a whole-of-committee basis. 

I also think that we should be able to reject sponsorships on a case by case basis. But I don't think we need machinery for that, I think it's usually obvious that a debate is needed when that opportunity arises. For e.g. for another society I was involved in, we WERE approached by Uber, but it was a super weird request and obviously needed debate. We ultimately rejected it.

**Comment by buildmaster** [comment]
Discussed Here https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2017/Committee-2017-04-02.md#societies-neutrality---kevin
