### ISSUE TITLE
Speaking at overseas conferences fund

### ISSUE THREAD

**Issue by annavlz** [JavaScript-NZ/Society-Meetings#57]
Following the amazing talk by Alex at the JS conf 2017:
- to promote NZ as a tech country globally we need more people to give talks at the conferences worldwide
- taking into consideration the location of NZ on the world map it is expensive
- we can create a fund to accumulate there money to help people whose talks are accepted but they have to decline because they/their companies can't afford to travel overseas
- find sponsors or/and put there any extra money society has
- create a committee that will choose from applicants based on predefined criteria
- make it available for society members only (so we have a benefit being a member)

**Comment by PrototypeAlex** [comment]
I wonder if this could tie into the corporate sponsorship issue, as it could be one of the benefits from sponsoring the society as a company. (Company logo on a slide?)

**Comment by jenofdoom** [comment]
As discussed at committee meeting on 19/03/19:

We currently don't have funds for this, it could be something that we could look to get sponsorship for, but we would need someone to step up to lead this effort. This person does not have to be on the committee, get in touch if this is something you're keen to work on with our help.
