### ISSUE TITLE
Forming working groups to address areas needing improvement

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#59]
Hi,

So with the responses I've got from javascript.org.nz/help after the Tech for Everyone talk, there are some common threads of how people want to help. Namely, "I would like to build a community in my town or city", and "I would love to help mentor someone".

On top of this, there are areas in which I could see some key people working on as a group, to push a movement forward. Namely, "Inclusivity in our community" and "Education for non-technical people".

The working group idea is something I've seen from the node.js community, from an outsiders point of view it's hard to gauge the success, but it appears that they're making leeway. Here's a link to the inclusivity node.js working group for reference: https://github.com/nodejs/inclusivity

So what I propose, to align with building a community that allows talent to thrive, is we setup the following working groups.

1. Everyone to be included (inclusivity)
2. People to up-skill and have career paths (mentorship)
3. Education of other groups, communities, students and children (education)
4. Creation and expansion of community hubs in towns and cities around NZ (networking? not sure what this one should be called)

I'm interested to hear if anyone else has ideas on working groups, or if any other working groups would be needed.

**Comment by buildmaster** [comment]
Discussed in April https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2017/Committee-2017-04-02.md#forming-working-groups-to-grow-our-community---alex

**Comment by jenofdoom** [comment]
Discussed in committee meeting 19/03/19 - a lot of this did get followed up on in one form or another e.g. Winter Mentor, closing this issue - but if people want to raise other specifics please feel free to do so.
