### ISSUE TITLE
Figure out how donations should work

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#6]
We've had offer for donations, outside of membership fees. We've had donations before, primarily from committee members, to setup specific things. But not general monetary donations that aren't for any specific purpose. We need to figure out how that should work.

**Comment by Unfocused** [comment]
Any donations are currently _not_ tax deductible. That would require registering as a charity. While free, it requires more work (paperwork, annual return) - so I don't think it's worth it yet.

**Comment by jenofdoom** [comment]
Discussed at committee meeting on 27-10-2015. Determined that:
- At this time we will not offer corporate memberships. However we will be looking into receiving corporate donations.
- Treasurer should do initial vetting of potential sponsors before presenting them to the committee
- We need a prospectus for potential sponsors. @PrototypeAlex is putting together a draft for consideration

**Comment by buildmaster** [comment]
@PrototypeAlex to share document outline with me
