### ISSUE TITLE
Create a better on boarding process so people are aware of our society code of conduct and rules

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#61]
Over the past week we’ve had conversations in our slack channel that have violated our CoC, this is probably inevitable for any large community, however, one thing noted was that a member was unaware there was a Code of Conduct in place, nor there was a society running the community slack channel.

This would suggest our on boarding process does not onboard new users into our community in an informative way.

I propose we have a mandatory ‘please accept our code of conduct’ before joining checkbox, and perhaps a brief introduction into the society, it’s goals and mission on the slack self invitation page.

This would help solve the problem to new members, however, we should also do a public channel announcement to #general, to ensure everyone understands they are part of an open community that has rules, a Code of Conduct, and a society running it.

**Comment by buildmaster** [comment]
@ootoovak did we set up a repetitive bot for this? 

We need to think about replacing slack in

**Comment by phenomnomnominal** [comment]
https://greetbot.io/ this looks cute

**Comment by buildmaster** [comment]
slack-in update has a checkbox for ensuring code of conduct agreement

**Comment by buildmaster** [comment]
We're going to cover this in #78 so closing this to have a single place to talk about moderation process which will also cover this a bit
