### ISSUE TITLE
Open up moderator roles to other members of the community

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#62]
The committee is somewhat constrained in size, and as the community grows, so will the amount of discourse that goes on in our slack channel.

To manage that the conversations stay on track and don’t breach the CoC I propose we open up some moderator roles, that way the onus of moderating the slack doesn’t fall on the heads of the committee members, whom most are already give up more than their fair share of community spoons.

Details of the roles will need to be created, and guidelines set in place, though I'm unsure of what they would be.

**Comment by ootoovak** [comment]
We doubled up on this issue so closing this one but will link to it here https://github.com/JavaScript-NZ/Society-Meetings/issues/62
