### ISSUE TITLE
Create a single point of communication to anyone wanting moderation in Slack

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#63]
During heated debates, it's not uncommon for a conversation to take a turn for the worse and become unpleasant, turn away other members, and in the worst case breach the code of conduct.

We need a way of any member to open up dialogue to the committee (or moderators), through a single point of entry.

Perhaps a @admins or @moderators group set in slack that contains all people capable of moderating.

Following from that, we should probably ensure some known and reasonable amount of turnaround time for a response and follow up action if need be. This may be somewhat tricker since we are all busy professionals (follow up issue to help resolve this).

**Comment by buildmaster** [comment]
Alias' are only available to paid slack.

Need to announce the use of the JS logo in slack status. and comms to committee to make sure everyone sets in

**Comment by buildmaster** [comment]
We're going to cover this in #78 so closing this to have a single place to talk about moderation process
