### ISSUE TITLE
Slack Moderators

### ISSUE THREAD

**Issue by ootoovak** [JavaScript-NZ/Society-Meetings#66]
Hi all,

So, after [the June JavaScript NZ Committee meeting](https://github.com/JavaScript-NZ/Society-Meetings/blob/7d5a1ec55eec5b74f15fb827a3334e08601851e3/2017/Committee-2017-06-11.md) we decided we wanted to open up our Slack to more modirators as the Committee memebers need help keeping an eye on it.

There is further discussion to be had in regards to the processes we would ask moderators to follow but it will mainly be around keeping an eye on the Slack channels and alerting the Committee if there are violations of the [Code of Conduct](http://javascript.org.nz/conduct).

Please let us know here if you are interested in joining the moderator team.

**Comment by ootoovak** [comment]
Closed duplicate issue: https://github.com/JavaScript-NZ/Society-Meetings/issues/62

**Comment by buildmaster** [comment]
We're going to cover this in #78 so closing this to have a single place to talk about moderation process
