### ISSUE TITLE
Suggestion to rename Dunedin City Council's internship programme

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#69]
Dunedin city council and various Otago education institutions created an internship programme a few years back to help students get into various industries, unfortunately, they were sold the name "Sexy Summer Jobs" at some stage, and that's what their brand revolves around.

I propose the society raises concern with the operators of "Sexy Summer Jobs" over the naming. 

It's become quite clear over discourse of this topic on our slack channel that it's not the best choice in name and offends various groups of people.

The idea and initiative is great, but I think as a community and established society, we're in a good position to be able to show them the problem and suggest they think about a rename.

**Comment by jenofdoom** [comment]
Voted in AGM 17/09/17 that @buildmaster will prepare a letter to be sent from the society.

**Comment by jwulf** [comment]
Agreed: silicon intelligences are genderless, and using a biological term is discriminatory.

**Comment by buildmaster** [comment]
I'm going to draft up a letter on behalf of the society here


To whom it may concern,
Javascript NZ Incorporated would like to raise our strong concerns and objections to the name of your internship program _Sexy Summer Jobs_, and implore you to consider renaming the program. As you may be aware the lack of diversity within STEM careers is a major concern to those of us that work within these fields and we feel, as a representative society of technologists throughout New Zealand, that it is incumbent upon us to try our hardest to increase the openness and inclusiveness of these career paths, a goal which the program naming actively undermines.

Internships are employment opportunities and, as such, branding programs in a sexual way undermines and discourages people from applying. There is a distinct power imbalance between employers and interns and we'd strongly urge you to remove any sexualised branding from such a process. Using terms such as Sexy and Speed Dating [https://sexysummerjobs.com/interns/guidelines/] suggest that the criteria for becoming an intern are more akin to being on Tinder than in employment. There are various internship programmes throughout the country who manage to have a similar process without using language that promotes any sexual connotations (summer of tech for example call their interviews just that, speed interviews)

We love seeing a successful internship program in operation but would urge you to rethink the name and branding that is associated to enable even more success in future.

**Comment by PrototypeAlex** [comment]
@buildmaster looks good to me, would be happy to see it shipped :shipit:

**Comment by ootoovak** [comment]
@buildmaster typo:
> to these us us that work within the fields

**Comment by buildmaster** [comment]
posted and emailed this

**Comment by jamesmacfie** [comment]
Here is the reply that we got back:

Dear Mr Evans,

Thank you for your letter and outlining your concerns.

The Sexy Summer Jobs Business Internship Programme was established in 2009 by the ICT business sector, tertiary providers, and the DCC to meet significant industry skills shortages. The internship programme meets business needs, create high value jobs, retains skills and talent in the city and continues to the economic growth of Dunedin.

The name of the programme was provided by students when the programme was established. It is intended to be used in the informal sense e.g. The term, "sexy" means exciting or appealing. For example "business magazines might not seem like the sexiest career choice" synonyms: exciting, stimulating, interesting, appealing, intriguing.

Sexy Summer Jobs has consistently delivered contributing to economic growth in Dunedin, feedback received about the programme is positive. The programme continues to retain its strong value proposition. Businesses utilise the programme to reduce the commercial risk in taking on an untried person. It provides the opportunity for market and product development, which would not ordinarily be executed, had the business not taken on an intern.

Now in it's eighth year, the programme is driven by business need, and while the programme started with an ICT focus, it now attracts a wide range of sectors and is now accessed by high growth business from 13 sectors to grow capabilities and stimulate employment. The top 3 business sectors 2016-2017 were ICT, Education/Research and BioTech/Health Technologies.

Business people also report high levels of satisfaction with the quality of interns for 2016-2017 (93% are very satisfied) and the quality of the programme (89& are very satisfied). Interns also indicated that the top three benefits of completing an internship are building relationships with business people and industry experts, working with experienced teams and adding value to a business. Normally over 50% of interns are offered employment post internship. In 2016/2017 of the 46 interns placed 32 were offered employment post-internship.

We have considered your letter and we are changing the name of the Speed Dating event to "Speed Interviews" to better reflect the activity and that will be implemented in 2018. However, we are unlikely to change the name of the programme as it is a recognised brand in the city and attracts a variety of students including international students from our tertiary institutions. In 2016/2017 season 51% of interns identified as female and 49% identified as male so it does not appear to be a deterrent on the demand side.
