### ISSUE TITLE
How to handle original 15 signing members

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#7]
When we registered as an incorporated society, we were required to have 15 signing members. Now that we're open for paid membership, not all of those original 15 are paid members. We need to figure out what to do about that.

**Comment by Unfocused** [comment]
My proposal is for anyone of the original 15 signers to automatically get free membership for the first year, and optionally take fees if they wish to pay them (that may or may not relate to #6)

**Comment by wrumsby** [comment]
> My proposal is for anyone of the original 15 signers to automatically get free membership for the first year, and optionally take fees if they wish to pay them

I like this proposal.

**Comment by buildmaster** [comment]
agreed

**Comment by buildmaster** [comment]
As decided we're moving to a recurring invoice model. myself and @PrototypeAlex will start moving existing members from 1st of Month
