### ISSUE TITLE
Make committee voting anonymous

### ISSUE THREAD

**Issue by jemmyw** [JavaScript-NZ/Society-Meetings#71]
Voting for committee member positions should be anonymous and not conducted in Slack, so as to avoid members being uncomfortable contributing votes.

**Comment by buildmaster** [comment]
true. Well suggested and not something I'd considered. We didn't have any alternative nominations this year so voting felt like a formality a little to me I will admit. But lets get suggestions for alternative vote methods.

**Comment by buildmaster** [comment]
@jemmyw were you concerned enough that the votes this year should be considered suspect?

**Comment by jemmyw** [comment]
@buildmaster no, I was not concerned. If there's only 1 candidate for a position then so long as they get 1 vote they win unless you official state there's an option of "none of the above".

However, it occurred to me that if there was more than 1 option I would feel under scrutiny voting one way or the other.

**Comment by PrototypeAlex** [comment]
Yes please, I think this is a great idea.

Do we have to change the rules to state the anonymity of voting? or do we just do it as our interpretation of voting.

**Comment by buildmaster** [comment]
On any given motion at a Society Meeting, the Chair/President shall in good faith determine whether to vote by:
Voices;
Show of hands;
Secret ballot; or
An alternative specified method indicated by the Chair/President at the start of the meeting.

**Comment by buildmaster** [comment]
so we can do anything that's generally agreed and a secret ballot is one of those

**Comment by jenofdoom** [comment]
We do need to ensure that votes are being performed by members of the society, so there might need to be a fair bit of infra setup to support anonymous voting.

**Comment by jemmyw** [comment]
Slack isn't restricted to members though, which makes the problem even worse because it means someone _will_ know how each person voted in order to ensure they were a member.

**Comment by jemmyw** [comment]
https://www.adoodle.org looks like a free service that might suffice. Presumably you have the list of member email addresses to seed it beforehand, then each member will have a personal token.

**Comment by jenofdoom** [comment]
We discussed this at the October committee meeting. We think there is a valid issue worth exploring here, but as it's more practical to discuss in view of the next AGM, we've set a reminder to re-raise this issue at the May 2018 committee meeting.

**Comment by jenofdoom** [comment]
@Kevnz to investigate

**Comment by jenofdoom** [comment]
Per https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2020/Committee-2020-11-23.md we've decided not to pursue this. Closing this issue.
