### ISSUE TITLE
Better password management for Society accounts

### ISSUE THREAD

**Issue by jenofdoom** [JavaScript-NZ/Society-Meetings#72]
Currently, the JavaScript NZ shared LastPass folder is at the max number of allowed members, and furthermore no-one on the committee has administrative control of it. I am exploring options for giving newer committee members access to the various passwords/credentials for the society.

**Comment by jenofdoom** [comment]
Free lastpass accounts offer no sharing at all.

**Comment by jenofdoom** [comment]
As discussed in committee meeting  19/03/19:

* A cruder solution may be the best option, for e.g. a keypass file that is sync'd via Google Drive
* Passbolt (open source) might also work, but would require self hosting
* It would be good to be able to cycle credentials periodically
* Kevin to investigate/set up the new solution, Jen to undertake cycling creds and adding to new solution when set up

**Comment by Unfocused** [comment]
Is the society still using this? I just realised that this is probably still attached to my personal LastPass account. Which was no problem for me, except I've been migrating to another service (Bitwarden) and have canceled my LastPass premium subscription - which I think will mean the sharing will stop working when that expires on 25th May.

If that is the case, and if the timing for that would cause difficulties for the society, let me know and I'll see about extending that timeframe.

**Comment by jenofdoom** [comment]
Hi Blair, thanks for letting us know. Yeah we've been tying to migrate that for a while but we couldn't figure out who owned it. I'll make sure we've got everything moved by the 25th. There is one thing you could do to help me, I'd like to double check who currently has access (I'll be asking the rest of the committee too but I'd ideally like to check both directions) - could you right click on the folder, check the Manage Folder option and email me a list of the people currently with access? You can send to secretary [at] javascript.org.nz

Cheers very much!

**Comment by Unfocused** [comment]
No worries. And done.

**Comment by jenofdoom** [comment]
Per https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2020/Committee-2020-11-23.md we've decided the currrent solution is fine for now. Closing this issue.
