### ISSUE TITLE
Moderation process

### ISSUE THREAD

**Issue by fabiancook** [JavaScript-NZ/Society-Meetings#78]
This is related to:

- https://github.com/JavaScript-NZ/Society-Meetings/issues/61
- https://github.com/JavaScript-NZ/Society-Meetings/issues/63

Currently it doesn't seem like we have too much of a process for moderation. 

With the moderator's channel being open up it would be cool if we could get a defined process for how we moderate and report on moderated posts/users. 

For example:

1. User mentions a "moderator" user on a post, tags with a moderation reaction, or directly messages a moderator, or a moderator sees something needing attention.  
2. Info about post is added to moderator channel
3. Discussion can be had as to how to proceed, for specific issues this may not be possible (for example if immediate action is required). 

Really we just need to be discussing what we are moderating and why (even if it is obvious)

**Comment by fabiancook** [comment]
Central place will be provided by https://github.com/WeAllJS/wheelie-slack-app, via an `/admin` command as described by @buildmaster

**Comment by jenofdoom** [comment]
Per https://github.com/JavaScript-NZ/Society-Meetings/blob/master/2020/Committee-2020-11-23.md the /admin command works fine now, there are a few other related issue we'll track separately. Closing this.
