### ISSUE TITLE
Nominations for Committee Members

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#9]
Please nominate members for the committee here (self nominations are fine). 

Or email @Unfocused if you wish to nominate anonymously

**Comment by Unfocused** [comment]
Current committee positions are kept up to date here:
https://github.com/JavaScript-NZ/Society-Documentation/blob/master/Committee.md

**Comment by Unfocused** [comment]
Appointed in the respective issues.
